module.exports.ERROR_CODES = {
    INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
    USER_LOCKED: 'USER_LOCKED',
    INVALID_SESSION: 'INVALID_SESSION',
    NO_TOKEN: 'NO_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS'
}

module.exports.UNIT_METRICS = {
    TIME_IN_MS: {
        SECOND: 1000,
        MINUTE: 60 * 1000,
        HOUR: 60 * 60 * 1000,
        DAY: 24 * 60 * 60 * 1000
    }
}
