module.exports.ERROR_CODES = {
    INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
    USER_LOCKED: 'USER_LOCKED',
    INVALID_SESSION: 'INVALID_SESSION',
    NO_TOKEN: 'NO_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    INVALID_DATA: 'INVALID_DATA',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND'
}

module.exports.UNIT_METRICS = {
    TIME_MS: {
        SECOND: 1000,
        MINUTE: 60 * 1000,
        HOUR: 60 * 60 * 1000,
        DAY: 24 * 60 * 60 * 1000
    },
    TIME_SECONDS: {
        MINUTE: 60,
        HOUR: 60 * 60,
        DAY: 24 * 60 * 60
    }
};

module.exports.PARAMS = {
    ADJUST_BALANCE: 'ADJUST_BALANCE',
    EDIT_ACCOUNT: 'EDIT_ACCOUNT'
}