module.exports.ERROR_CODES = {
    INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
    USER_LOCKED: 'USER_LOCKED',
    INVALID_SESSION: 'INVALID_SESSION',
    NO_TOKEN: 'NO_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED'
}